language: ruby
sudo: required
dist: trusty
before_install: gem install bundler
install:
  - bundle install --retry=3
cache: bundler
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - jruby-19mode
  - rbx-3
  - ruby-head
matrix:
  allow_failures:
  - rvm: rbx-3
  - rvm: ruby-head
addons:
  apt:
    packages:
      - haveged
